#!/usr/bin/env python3
"""Prepare (never submit) one discovery-350k training attempt as an immutable run_handoff handoff.

python3 campaigns/2026-10-08-discovery-350k/tools/prepare_attempt.py ARM ATTEMPT [--branch BRANCH]
    [--stage wave1|search|confirm|followup] [--stop-epoch 1000] [--runtime-factor 1.0]
    [--resume-from RUN_NAME]

ARM is a config of the branch's campaigns/d350/index.json without the 'd350-' prefix
(baseline-e-350k-s1, reference-e-5m-s1, or a candidate's). The code is the branch's committed tree
(git archive of BRANCH, default main), never the working tree. Writes, inside this campaign only:
  manifests/<arm>-a<attempt>/{configmap,job,brief}.json   inputs to run_handoff prepare
  handoffs/rh-*                                           tools/run_handoff.py prepare output (offline)
  attempts/<arm>-a<attempt>.json                          the attempt record prepare_score.py reads
The last stdout line is the absolute handoff directory. Nothing calls kubectl.

Job shape (pilot freeze_p.py R1 r3 options, reused): one arm per RTX 3090, podFailurePolicy
(Ignore DisruptionTarget; FailJob 10; FailIndex 5/76/124/137/143), backoffLimitPerIndex 1, pod
activeDeadlineSeconds = 47 s x epochs to run x runtime factor (1,000 epochs: 47,000 s),
run_pack.py <pack> <stop epoch>, GPU fingerprint gate, node exclusions of the pilot plus r3.
Labels: user=kai, campaign=discovery-350k-20261008, app=kai-d350-train, bnjettag.io/role=train,
bnjettag.io/stage=<stage>, bnjettag.io/attempt, bnjettag.io/arms-per-pod=1.

--resume-from RUN_NAME continues that attempt's run directory from its latest committed checkpoint:
to a later stop epoch (the follow-up stage), or to the same stop epoch (relaunch of an unfinished run,
as the pilot's r2/r3 relaunches did). run_study/ablation resume only with the same config
hash, data hash and code manifest sha, so the branch commit must have the same bundle manifest sha
and config as the source attempt; the stop epoch may not be earlier than the source's. The resumed
run keeps its run directory and W&B run id (BNJ_STAGE unchanged).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import d350_common as dc  # noqa: E402


def brief_for(*, cfg_name, arm, attempt, stage, stop, start, deadline, factor, commit, branch, run_root,
              resume_from, bundle_sha, hyp, target, config_text=None):
    start_text = ('starts from initialization at epoch 0 in a new run directory' if not resume_from else
                  f'resumes {resume_from} from its latest committed checkpoint (deadline counted from epoch {start}) '
                  'in the same run directory and W&B run id')
    return {
        'purpose': f'discovery-350k {stage} attempt {attempt}: arm {arm} ({hyp}, E, target {target}), {start_text}, '
                   f'trained to stop epoch {stop} on one RTX 3090.',
        'changes': f'Code: code/ commit {commit} (branch {branch}), bundle {bundle_sha[:12]}; '
                   + (config_text or f'config {cfg_name} generated by '
                      'campaigns/d350/generate.py from pilot1005-h1-e-350k-c-s1 (only identity keys and, for the reference, '
                      'the EBOPs target differ; configs/README.md).')
                   + ' Job shape from the pilot freeze_p.py r3 options; run '
                   f'outputs under {run_root}, never the pilot run root.',
        'approval_ref': dc.APPROVAL_REF,
        'scientific_gate': {'status': 'cleared', 'reference': dc.GATE_REFERENCE},
        'production_gate': {'status': 'pending', 'reference': 'K3: a 7,000-epoch production run is Kai\'s separate approval'},
        'runs': [{'name': cfg_name, 'config_path': f'code/campaigns/d350/configs/{cfg_name}.json'}],
        'expected_metrics': [{'name': 'eval/score.py primary', 'split': f'validation n=62000, epochs < {stop}',
                              'expectation': 'reported, not predicted (PROPOSAL.md §4); scored by a separate CPU Job'}],
        'stop_rules': [
            {'condition': 'divergence, nonfinite metrics, epoch-0 divergence, fingerprint mismatch',
             'action': 'existing-runner-guard', 'approval_ref': 'run_pack/ablation guards in the frozen bundle'},
            {'condition': f'pod activeDeadlineSeconds {deadline} / run_pack timeout or a training-phase failure',
             'action': 'existing-runner-guard',
             'approval_ref': 'final for the index (podFailurePolicy FailIndex on 5, 76, 124, 137, 143); '
                             'backoffLimitPerIndex 1 only for a pre-arm failure (exit 75, within 600 s)'},
            {'condition': 'CANARY_* FAIL or CONTROLLER_AUDIT FAIL in a MONITOR line', 'action': 'notify-only',
             'approval_ref': 'monitor_p.py (byte copy in campaigns/d350)'}],
        'outputs': [f'{run_root}/runs/{cfg_name}',
                    f'wandb://kayamaguchi-uc-san-diego/BNJetTag-ChangRecipe/{dc.CAMPAIGN_LABEL}'],
        'limitations': ['Discovery run: no number is a result before a VERIFY.md.',
                        f'Deadline {deadline} s = {dc.S_PER_EPOCH} s x {stop - start} epochs x {factor}.',
                        'W&B run id is keyed by config name and BNJ_STAGE; a fresh re-attempt of the same arm reuses it '
                        '(PREFLIGHT.md, unverified item).'],
        'decision_ref': 'campaigns/2026-10-08-discovery-350k/PROPOSAL.md §3, §8',
        'study_ref': 'campaigns/2026-10-08-discovery-350k/PROPOSAL.md',
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('arm')
    ap.add_argument('attempt', type=int)
    ap.add_argument('--branch')
    ap.add_argument('--stage', default='wave1', choices=dc.STAGES)
    ap.add_argument('--stop-epoch', type=int, default=1000)
    ap.add_argument('--runtime-factor', type=float, default=1.0)
    ap.add_argument('--resume-from', metavar='RUN_NAME')
    ap.add_argument('--runtime-justification', metavar='TEXT',
                    help='required above BRIEF operations.runtime_factor_notify: why this factor')
    ap.add_argument('--timing-evidence', metavar='PATH',
                    help='required above runtime_factor_notify: file with the measured timing')
    ap.add_argument('--config-text', help='brief: config provenance sentence (default: the generate.py one)')
    args = ap.parse_args(argv)
    if args.attempt < 1:
        dc.fail('attempt must be >= 1')
    if args.runtime_factor > dc.RUNTIME_FACTOR_NOTIFY:
        ev = Path(args.timing_evidence) if args.timing_evidence else None
        if not (args.runtime_justification and ev and ev.is_file()):
            dc.fail(f'runtime factor {args.runtime_factor} > {dc.RUNTIME_FACTOR_NOTIFY} (runtime_factor_notify) needs '
                    '--runtime-justification and an existing --timing-evidence file')
    if not 1.0 <= args.runtime_factor <= dc.RUNTIME_FACTOR_MAX:
        dc.fail('runtime factor must be within [1, 3]')
    branch = args.branch or dc.default_branch()
    commit = dc.resolve(branch)
    fp = dc.load_freeze_p()
    run_name = f'{args.arm}-a{args.attempt}'
    with dc.tmpdir() as tmp:
        tree = dc.export_tree(commit, Path(tmp) / 'tree')
        index = json.loads((tree / 'campaigns' / 'd350' / 'index.json').read_text())['runs']
        cfg_name = f'd350-{args.arm}'
        row = next((r for r in index if r['name'] == cfg_name), None)
        if row is None:
            dc.fail(f'{cfg_name} not in campaigns/d350/index.json at {commit[:12]}')
        cfg_bytes = (tree / 'campaigns' / 'd350' / 'configs' / row['file']).read_bytes()
        if dc.sha(cfg_bytes) != row['config_sha256']:
            dc.fail(f'{row["file"]} sha differs from index.json')
        cfg = json.loads(cfg_bytes)
        snap = int(cfg['experiment']['snapshot_every_epochs'])
        if args.stop_epoch <= 0 or args.stop_epoch % snap or args.stop_epoch > int(cfg['train']['epochs']):
            dc.fail(f'stop epoch {args.stop_epoch} must be a positive multiple of snapshot_every_epochs {snap} '
                    f'and <= train.epochs')
        payload, files, msha = dc.bundle(fp, tree)
    bundle_sha = dc.sha(payload)
    start, run_root = 0, f'{dc.PVC_ROOT}/attempts/{run_name}'
    if args.resume_from:
        src_path = dc.CAMP / 'attempts' / f'{args.resume_from}.json'
        if not src_path.is_file():
            dc.fail(f'no attempt record {src_path.name}')
        src = json.loads(src_path.read_text())
        if src['arm'] != args.arm:
            dc.fail(f'{args.resume_from} is arm {src["arm"]}, not {args.arm}')
        if src['manifest_sha256'] != msha or src['config_sha256'] != row['config_sha256']:
            dc.fail('resume needs the same code manifest sha and config as the source attempt '
                    f'(source {src["manifest_sha256"][:12]}/{src["config_sha256"][:12]}, '
                    f'now {msha[:12]}/{row["config_sha256"][:12]}): ablation.restore_checkpoint would refuse')
        if args.stop_epoch < src['stop_epoch']:
            dc.fail(f'stop epoch {args.stop_epoch} is earlier than the source stop epoch {src["stop_epoch"]}')
        # later stop: continue a run that reached its stop epoch (follow-up); same stop: relaunch an
        # unfinished run from its latest checkpoint (the pilot r2/r3 pattern). The deadline covers the
        # epochs from the source's stop (follow-up) or from the source's own start (relaunch, conservative).
        start = src['stop_epoch'] if args.stop_epoch > src['stop_epoch'] else src['start_epoch']
        run_root = src['run_root']
    if not run_root.startswith(dc.PVC_ROOT + '/') or run_root.startswith(dc.PILOT_PVC_ROOT):
        dc.fail(f'run root {run_root} outside {dc.PVC_ROOT}')
    deadline = int(round(dc.S_PER_EPOCH * (args.stop_epoch - start) * args.runtime_factor))
    job_name = f'kai-d350-{args.arm}-a{args.attempt}'
    if len(job_name) > 52:
        dc.fail(f'job name {job_name} longer than 52 characters')
    for value, what in ((job_name, 'job name'), (args.stage, 'stage'), (str(args.attempt), 'attempt'),
                        (args.arm, 'arm')):
        dc.check_label(value, what)
    tags = f'd350,discovery-350k,{args.stage},a{args.attempt},validation-only'
    nodes = dc.point_fp(fp, run_root, args.stop_epoch, deadline, tags)
    cm_name = 'kai-d350-code-' + bundle_sha[:10]
    # The code ConfigMap is content-addressed by bundle: its annotation names the commit only, so a
    # relaunch of the same commit from another branch reuses the identical object.
    cm = dc.configmap(fp, cm_name, payload, msha, f'code/ commit {commit}; base {dc.base_commit()}')
    script = fp.header(bundle_sha, msha, cpu=False, trap=fp.pod_exit_trap()) + fp.pilot_tail(row)
    job = fp.pilot_job(job_name, row, cm_name, script)
    labels = {'user': 'kai', 'campaign': dc.CAMPAIGN_LABEL, 'app': 'kai-d350-train', 'bnjettag.io/role': 'train',
              'bnjettag.io/stage': args.stage, 'bnjettag.io/attempt': str(args.attempt), 'bnjettag.io/arms-per-pod': '1'}
    job['metadata']['labels'] = dict(labels)
    job['spec']['template']['metadata']['labels'] = dict(labels)
    ann = job['metadata']['annotations']
    ann['bnjettag.io/arm'] = (f"{args.arm} a{args.attempt} {row['hypothesis']} E budget {row['budget']} warmup "
                              f"{row['warmup']} stop {args.stop_epoch}")
    ann['bnjettag.io/stop-epoch'] = str(args.stop_epoch)
    ann['bnjettag.io/expected-start-epoch'] = str(start)
    ann['bnjettag.io/run-dir'] = f'{run_root}/runs/{cfg_name}'
    ann['bnjettag.io/code-commit'] = commit
    ann['bnjettag.io/runtime-factor'] = repr(args.runtime_factor)
    # checks on the built object: the pilot shape and this campaign's settings
    spec, pod = job['spec'], job['spec']['template']['spec']
    # Hard GPU-hour bound (BRIEF gpu_bound_mode 'hard'): Kubernetes ends the whole Job, retries and
    # pods replaced after disruptions included, at the Job deadline. With one pod at a time and
    # replacement only after a pod is terminal, GPU time <= 1 GPU x Job deadline (+ grace).
    spec['activeDeadlineSeconds'] = deadline * (spec['backoffLimitPerIndex'] + 1)
    assert spec.get('parallelism') == 1 and spec.get('completions') == 1
    assert spec.get('podReplacementPolicy') == 'Failed'
    assert pod['activeDeadlineSeconds'] == deadline and spec['backoffLimitPerIndex'] == 1
    assert [r['action'] for r in spec['podFailurePolicy']['rules']] == ['Ignore', 'FailJob', 'FailIndex']
    expr = pod['affinity']['nodeAffinity']['requiredDuringSchedulingIgnoredDuringExecution']['nodeSelectorTerms'][0]['matchExpressions']
    assert expr[0]['values'] == ['NVIDIA-GeForce-RTX-3090'] and expr[1]['values'] == nodes
    assert pod['containers'][0]['resources']['limits']['nvidia.com/gpu'] == '1'
    script_text = pod['containers'][0]['args'][0]
    assert f'run_pack.py "$PACKS" {args.stop_epoch}' in script_text and f'BNJ_RUN_ROOT={run_root} ' in script_text
    assert dc.PILOT_PVC_ROOT not in script_text and 'BNJ_RSS_GATE' not in script_text
    assert script_text.index('fingerprint_check.py --run') < script_text.index('run_pack.py')
    out = dc.CAMP / 'manifests' / run_name
    brief = brief_for(cfg_name=cfg_name, arm=args.arm, attempt=args.attempt, stage=args.stage, stop=args.stop_epoch,
                      start=start, deadline=deadline, factor=args.runtime_factor, commit=commit, branch=branch,
                      run_root=run_root, resume_from=args.resume_from, bundle_sha=bundle_sha, hyp=row['hypothesis'],
                      target=row['budget'], config_text=args.config_text)
    for name, value in (('configmap.json', cm), ('job.json', job), ('brief.json', brief)):
        dc.write_same(out / name, dc.enc(value))
    handoff, record_sha, job_sha = dc.run_handoff_prepare(fp, out / 'job.json', out / 'configmap.json', out / 'brief.json')
    record = {'schema': 1, 'run_name': run_name, 'arm': args.arm, 'attempt': args.attempt, 'stage': args.stage,
              'branch': branch, 'commit': commit, 'base_commit': dc.base_commit(), 'bundle_sha256': bundle_sha,
              'manifest_sha256': msha, 'configmap': cm_name, 'config_name': cfg_name, 'config_sha256': row['config_sha256'],
              'target_ebops': row['budget'], 'stop_epoch': args.stop_epoch, 'start_epoch': start,
              'resume_from': args.resume_from, 'runtime_factor': args.runtime_factor, 'pod_deadline_s': deadline,
              'run_root': run_root, 'run_dir': f'{run_root}/runs/{cfg_name}', 'job': job_name,
              'handoff': str(handoff.relative_to(dc.CAMP)), 'record_sha256': record_sha, 'job_json_sha256': job_sha,
              'excluded_nodes': nodes, 'status': 'prepared_not_submitted'}
    dc.write_same(dc.CAMP / 'attempts' / f'{run_name}.json', dc.enc(record))
    if args.runtime_factor > dc.RUNTIME_FACTOR_NOTIFY:
        # Recorded beside the immutable attempt record (whose form is unchanged for ordinary factors).
        note = {'run_name': run_name, 'job': job_name, 'runtime_factor': args.runtime_factor,
                'pod_deadline_s': deadline, 'justification': args.runtime_justification,
                'timing_evidence': str(Path(args.timing_evidence).resolve())}
        (dc.CAMP / 'attempts' / f'{run_name}.runtime-justification.json').write_text(json.dumps(note, indent=2) + '\n')
        dc.HARNESS.record(dc.CAMP, dict(note, type='runtime_allowance'))
        dc.HARNESS.notify(dc.CAMP, dc.POLICY, f'{job_name}: runtime factor {args.runtime_factor} above '
                          f'{dc.RUNTIME_FACTOR_NOTIFY}; deadline {deadline} s; reason: {args.runtime_justification[:200]}')
    print('PREPARED_ATTEMPT', run_name, job_name, 'commit', commit[:12], 'bundle', bundle_sha[:12], 'deadline_s', deadline)
    print(handoff)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
