Backend: Vitis
ClockPeriod: 2.5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: true
    Precision: fixed<24,12>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
InputShapes:
  input_1:
  - 8
  - 3
KerasModel: !keras_model '/Users/kaiyamaguchi/Desktop/bnjettag-lab/local/synthesis-r4-gradual-20260917/export/hls_prj_rf1/keras_model.keras'
OutputDir: /Users/kaiyamaguchi/Desktop/bnjettag-lab/local/synthesis-r4-gradual-20260917/export/hls_prj_rf1
OutputPredictions: null
OutputShapes:
  layer83_out:
  - 5
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: e948770c
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
